#!/usr/bin/env python3
"""
Vinyl scratch removal CLI wrapper script.
"""
import sys
import os

# Add parent directory to path to find vinyl_cli
parent_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, parent_dir)

from vinyl_cli import main

if __name__ == '__main__':
    sys.exit(main())
